### ISSUE TITLE
How to get path parameter inside a Handler

### ISSUE THREAD

**Issue by agrizzli** [Articus/PathHandler#2]
Hello Articus,

I am using PathHandler with OpenAPI generator and have created some Handlers to handle paths with paramaters, but not in query. Example:

```php
/**
 * @PHA\Route(pattern="/country/{byId}")
 */
class CountryById
{
    /**
     * Get country by id
     * @PHA\Get()
     * @PHA\Producer(name=PHProducer\Transfer::class, mediaType="application/json")
     * @param ServerRequestInterface $request
     * @return \App\DTO\Country
     */
    public function getCountry(ServerRequestInterface $request): \App\DTO\Country
    {
       // How to get byId parameter from path herein ?
    }
}
```

There is very good example from you how to get provided query parameters via an extra class. But how can I get parameter ```byId``` from path?

Would be great to have an example. I am a beginner in Zend Expressive.

**Comment by Articus** [comment]
Hi,
If you want to get only matched parameter from route, [usual Zend Expressive way](https://docs.zendframework.com/zend-expressive/v3/features/router/intro/#retrieving-matched-parameters) would be `$byId = $request->getAttribute('byId');` inside your handler method. Or you may get [`\Zend\Expressive\Router\RouteResult` attribute](https://docs.zendframework.com/zend-expressive/v3/features/router/intro/#retrieving-the-matched-route), something like:
```PHP
$routeResult = $request->getAttribute(\Zend\Expressive\Router\RouteResult::class);
if (!($routeResult instanceof \Zend\Expressive\Router\RouteResult))
{
	throw new \LogicException('Failed to find routing result.');
}
$data = $routeResult->getMatchedParams();
$byId = $data['byId']; //Matched parameter value
```
You may also want to consider creating an [attribute class](https://pathhandler.readthedocs.io/en/latest/attributing/) that will add something more useful to request like database data fetched by this id. [Transfer attribute](https://github.com/Articus/PathHandler/blob/master/src/Articus/PathHandler/Attribute/Transfer.php#77)  may be a good example.

**Comment by agrizzli** [comment]
Thank you! Great! 

```$byId = $request->getAttribute('byId');``` This was, what I was looking for!

**Comment by Articus** [comment]
So I guess the question is answered :) Closing this issue then.
