### ISSUE TITLE
Extend super class in Handlers and DTOs in junction with openapi-generator/php-ze-ph

### ISSUE THREAD

**Issue by agrizzli** [Articus/PathHandler#3]
Hi Articus,

I know that might be not correct place for that question, however since you promote PathHandler in junction with OpenAPI generator, I woul like to place it.

Is there any possibility to tell ```php-ze-ph``` plugin to generate Hander and DTOs, which extend another super class? For Handler like:

```php
/**
 * @PHA\Route(pattern="/example_item/{byId}")
 */
class ExampleItemById extends AbstractHandler {
   // ...
}
```

Or for DTOs:

```php
use Articus\DataTransfer\Annotation as DTA;

/**
 */
class ExampleItem extends AbstractDTO
{
  // ...
}
```
Thanks to #2, I know now, that that I can use Attributing to add something to Request object, but I would like also to use inheritance in this case. Is this possible? An answer would please me a lot!

**Comment by Articus** [comment]
There is no such feature in `php-ze-ph` generator right now. It is possible to add this functionality using OAS vendor extensions but it might be a bit tricky to specify all possible scenarios - like use abstract class or trait, which properties should be moved to that abstract class/trait... And you might ended up with spec and code being too losely coupled. 
After all `php-ze-ph` (as other server generators and unlike client generators) creates only stub that you have to enhance and modify for your needs. For example, I used to convert specific DTO classes to Doctrine entities manually :)

But if you have some enormous amount of DTO's check [`--template-dir` parameter](https://github.com/OpenAPITools/openapi-generator#3---usage). You can copy [`php-ze-ph` templates](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/php-ze-ph), adjust them for your liking and use openapi-generator with adjusted version.

**Comment by agrizzli** [comment]
It is a sound! Will check it out! Thanks!

**Comment by Articus** [comment]
So I guess the question is answered :) Closing this issue then.
